project:
  type: website
  output-dir: docs

website:
  title: "Research Support Diary"
  navbar:
    background: '#000000'
    foreground: '#ffffff'
    right:
      - about.qmd
      - icon: github
        href: https://github.com/StefanoRapisarda
      - icon: linkedin
        href: https://www.linkedin.com/in/stefanorapisarda/
format:
  html:
    theme: yeti
    css: styles.css



